init:
  - git config --global core.autocrlf input
  - ps: |
      tree /a "C:\ProgramData\Docker"

version: 0.65.{build}

skip_tags: true

before_build:
  - ps: |
      docker pull $env:RABBITMQ_DOCKER_IMAGE_NAME
      $cid = docker run -d $env:RABBITMQ_DOCKER_IMAGE_NAME
      $hostip = docker inspect -f "{{ .NetworkSettings.Networks.nat.IPAddress }}" $cid
      $env:RABBITMQ_URL = "amqp://guest:guest@${hostip}:5672"
  - ps: |
      docker pull $env:ELASTICSEARCH_DOCKER_IMAGE_NAME
      $cid = docker run -d $env:ELASTICSEARCH_DOCKER_IMAGE_NAME
      $hostip = docker inspect -f "{{ .NetworkSettings.Networks.nat.IPAddress }}" $cid
      $env:ELASTICSEARCH_URL = "http://${hostip}:9200"
  - ps: |
      docker pull $env:EVENTSTORE_DOCKER_IMAGE_NAME
      $cid = docker run -d $env:EVENTSTORE_DOCKER_IMAGE_NAME
      $hostip = docker inspect -f "{{ .NetworkSettings.Networks.nat.IPAddress }}" $cid
      $env:EVENTSTORE_URL = "tcp://admin:changeit@${hostip}:1113"

build_script:
  - cmd: powershell -NoProfile -ExecutionPolicy unrestricted -Command .\build.ps1 -Target "All"

image: Visual Studio 2017

environment:
  HELPZ_POSTGRESQL_PASS: Password12!
  RABBITMQ_DOCKER_IMAGE_NAME: idubnori/rabbitmq-windows:3.6.9
  ELASTICSEARCH_DOCKER_IMAGE_NAME: sixeyed/elasticsearch:5.6.0-nanoserver-sac2016
  EVENTSTORE_DOCKER_IMAGE_NAME: idubnori/eventstore:4.1.1-hotfix1-windowsservercore

test: off

artifacts:
  - path: Build\Packages\*.nupkg

services:
  - mssql2014
  - postgresql101

on_success:
- "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
- pip install codecov
- codecov -f "Build\\Reports\\opencover-results.xml"

nuget:
  account_feed: false
  project_feed: false
  disable_publish_on_pr: true

deploy:
  - provider: NuGet
    api_key:
      secure: +YlrKmWps7RJVPU4s7B4HWNL9cZXaUVdiNJInli9IZPlTP+J0CyHsUvcDY8haE+b
    skip_symbols: false
    on:
      branch: master
  - provider: GitHub
    artifact: /.*\.(nupkg|zip)/
    auth_token:
      secure: f+y+RL1ETsxIbYKlliZrmXpfr1wvEVNhGGEOYyl2K8ryz02WxXL+kLe7pu53Kc8r
    tag: v$(appveyor_build_version)
    draft: true
    prerelease: false
    on:
      branch: master
