resources:
  containers:
  - container: dev1
    image: elasticsearch:5.6.11-alpine
    options: --hostname es-test
jobs:
- job: job_container
  pool:
    vmImage: ubuntu-16.04
  steps:
  - script: |
          docker run -d -p 9200:9200 -p 9300:9300 --name es elasticsearch:5.6.11-alpine
  - script: |
          ifconfig
          sleep 15
          curl http://localhost:9200 --connect-timeout 60 --retry 5 -sL
          sleep 180

- job: job_build
  pool:
    vmImage: vs2017-win2016
  steps:
  - powershell: |
          ipconfig

          cinst curl -y --no-progress
          sal curl (Join-Path $env:ChocolateyInstall "bin\curl.exe") -O AllScope

          curl --connect-timeout 30 --retry 5 "http://10.1.0.4:9200"
          curl --connect-timeout 30 --retry 5 "http://172.17.0.2:9200"
          Start-Sleep -s 60
          curl --connect-timeout 30 --retry 5 "http://172.17.0.2:9200"
          curl --connect-timeout 30 --retry 5 "http://10.1.0.4:9200"

