# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

jobs:
- job: Build
  pool:
    name: Hosted VS2017

  variables:
    solution: '**/*.sln'
    buildPlatform: 'Any CPU'
    buildConfiguration: 'Release'

  steps:
  - task: NuGetToolInstaller@0

  - task: NuGetCommand@2
    inputs:
        restoreSolution: '$(solution)'

  - task: VSBuild@1
    inputs:
      solution: '$(solution)'
      platform: '$(buildPlatform)'
      configuration: '$(buildConfiguration)'
      maximumCpuCount: true

  - task: CopyFiles@2
    displayName: 'Functional tests to: ArtifactStagingDirectory'
    inputs:
        targetPath: Source
        Contents: '**/*.Tests/bin/**/*'
        TargetFolder: '$(Build.ArtifactStagingDirectory)/tests'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: ArtifactStagingDirectory'
    inputs:
        artifactName: 'tests'
        PathtoPublish: '$(Build.ArtifactStagingDirectory)/tests'

  # - task: VSTest@2
  #   inputs:
  #     platform: '$(buildPlatform)'
  #     configuration: '$(buildConfiguration)'


- job: Test
  pool:
    name: Hosted VS2017
  steps:
  - checkout: none

  - task: DownloadBuildArtifacts@0
    displayName: 'Download tests Artifacts'
    inputs:
      artifactName: 'tests'
      downloadPath: '$(System.DefaultWorkingDirectory)/tests/'

  - task: VSTest@2
    displayName: 'VsTest - testAssemblies'
    inputs:
      testAssemblyVer2: '**\*Tests.dll'
      runOnlyImpactedTests: false
      runInParallel: true
      codeCoverageEnabled: true

  dependsOn: Build
  condition: succeeded()