resources:
  containers:
  - container: dev1
    image: elasticsearch:5.6.11-alpine
    options: --hostname es-test
jobs:
- job: job_container
  pool:
    vmImage: ubuntu-16.04
  steps:
  - script: |
          docker run -d -p 9200:9200 -p 9300:9300 --name es elasticsearch:5.6.11-alpine
  - script: |
          sleep 15
          curl http://localhost:9200 --connect-timeout 60 --retry 5 -sL
  - script: |
          ELASTICSEARCH_URL="http://${elasticsearch_ip}:9200"
          dotnet test Source\EventFlow.Elasticsearch.Tests