# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

jobs:
- job: Build
  pool:
    name: Hosted VS2017

  variables:
    solution: '**/*.sln'
    buildPlatform: 'Any CPU'
    buildConfiguration: 'Release'
    version: 0.68.0

  steps:
  - powershell: |
      .\build.ps1 -Target All;
    displayName: 'PowerShell Script'