version: '3'

services:
  rabbitmq:
    image: rabbitmq:3.7
    container_name: rabbitmq-ef

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.0
    container_name: elasticsearch-ef

  eventstore:
    image: eventstore/eventstore
    container_name: eventstore-ef

networks:
  default:
    external:
      name: nat