version: '3'

services:
  rabbitmq:
    image: idubnori/rabbitmq-windows:3.6.9
    container_name: rabbitmq-ef
    restart: always

  elasticsearch:
    image: sixeyed/elasticsearch:5.6.0-nanoserver-sac2016
    container_name: elasticsearch-ef
    restart: always

  eventstore:
    image: idubnori/eventstore:4.1.1-hotfix1-windowsservercore
    container_name: eventstore-ef
    restart: always

networks:
  default:
    external:
      name: nat